openapi: 3.0.3
info:
  title: Family Budget API
  description: REST API for managing household budgets, categories, transactions, and financial summaries.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8080/api
    description: Local Development Server

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Budget:
      type: object
      properties:
        budgetId:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          minLength: 1
          maxLength: 200
          pattern: "^[A-Za-z0-9 ]+$"
          example: "Monthly Household Budget 1"
        categories:
          type: array
          description: "List of categories associated with this budget."
          items:
            $ref: "#/components/schemas/Category"
        transactions:
          type: array
          description: "List of transactions associated with this budget."
          items:
            $ref: "#/components/schemas/Transaction"


    Category:
      type: object
      properties:
        categoryId:
          type: integer
          format: int64
          example: 1
        budgetId:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          minLength: 1
          maxLength: 200
          pattern: "^[A-Za-z ]+$"
          example: "Groceries"

    Transaction:
      type: object
      properties:
        transactionId:
          type: integer
          format: int64
          example: 101
        budgetId:
          type: integer
          format: int64
          example: 1
        categoryId:
          type: integer
          format: int64
          nullable: true
          example: 1
        description:
          type: string
          minLength: 1
          maxLength: 200
          pattern: "^[A-Za-z ]+$"
          example: "Supermarket Shopping"
        amount:
          type: number
          format: double
          example: 150.00
        date:
          type: string
          format: date
          example: "2025-01-17"
        type:
          type: string
          enum: [EXPENSE, INCOME, MOVE]
          example: "EXPENSE"

    PeriodSummary:
      type: object
      properties:
        startDate:
          type: string
          format: date
          example: "2024-01-01"
        endDate:
          type: string
          format: date
          example: "2024-12-31"
        totalExpenses:
          type: number
          format: double
          example: 500.00
        totalIncome:
          type: number
          format: double
          example: 1000.00
        surplus:
          type: number
          format: double
          example: 500.00
        expenseCategories:
          type: array
          items:
            $ref: "#/components/schemas/CategorySummary"
        incomeCategories:
          type: array
          items:
            $ref: "#/components/schemas/CategorySummary"

    CategorySummary:
      type: object
      properties:
        categoryName:
          type: string
          example: "Groceries"
        amount:
          type: number
          format: double
          example: 150.00

paths:
  /budgets:
    get:
      summary: Get all budgets
      operationId: getBudgets
      responses:
        "200":
          description: List of budgets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Budget"

    post:
      summary: Create a new budget
      operationId: createBudget
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Budget"
      responses:
        "201":
          description: Budget created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Budget"

  /budgets/{budgetId}:
    get:
      summary: Get budget details
      operationId: getBudget
      parameters:
        - name: budgetId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Budget details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Budget"
        "404":
          description: Budget not found

    put:
      summary: Update an existing budget
      description: Updates the budget, including its name and associated collections (categories, transactions).
      operationId: updateBudget
      parameters:
        - name: budgetId
          in: path
          required: true
          description: ID of the budget to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Budget"
      responses:
        "200":
          description: Budget updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Budget"
        "400":
          description: Invalid request data
        "404":
          description: Budget not found
        "401":
          description: Unauthorized access

    delete:
      summary: Delete a budget
      operationId: deleteBudget
      parameters:
        - name: budgetId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Budget deleted successfully
        "404":
          description: Budget not found

  /budgets/{budgetId}/categories:
    get:
      summary: Get all categories for a budget
      operationId: getCategories
      parameters:
        - name: budgetId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"

    post:
      summary: Add a category to a budget
      operationId: createCategory
      parameters:
        - name: budgetId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        "201":
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"

  /budgets/{budgetId}/categories/{categoryId}:
    put:
      summary: Update an existing category
      description: Updates the details of a category within a specific budget.
      operationId: updateCategory
      parameters:
        - name: budgetId
          in: path
          required: true
          description: ID of the budget the category belongs to
          schema:
            type: integer
            format: int64
        - name: categoryId
          in: path
          required: true
          description: ID of the category to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        "200":
          description: Category updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "400":
          description: Invalid category ID or request body
        "404":
          description: Category not found
        "401":
          description: Unauthorized access

    delete:
      summary: Delete a category by ID
      description: Removes a category from a specific budget.
      operationId: deleteCategory
      parameters:
        - name: budgetId
          in: path
          required: true
          description: ID of the budget the category belongs to
          schema:
            type: integer
            format: int64
        - name: categoryId
          in: path
          required: true
          description: ID of the category to delete
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Category deleted successfully (No Content)
        "400":
          description: Invalid category ID
        "404":
          description: Category not found
        "401":
          description: Unauthorized access

  /budgets/{budgetId}/transactions:
    post:
      summary: Create a new transaction
      description: Adds a new transaction to a specific budget.
      operationId: createTransaction
      parameters:
        - name: budgetId
          in: path
          required: true
          description: ID of the budget the transaction belongs to
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        "201":
          description: Transaction created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "400":
          description: Invalid transaction data
        "401":
          description: Unauthorized access

  /budgets/{budgetId}/transactions/{transactionId}:
    get:
      summary: Get a transaction by ID
      description: Retrieves a specific transaction by its ID.
      operationId: getTransaction
      parameters:
        - name: budgetId
          in: path
          required: true
          description: ID of the budget the transaction belongs to
          schema:
            type: integer
            format: int64
        - name: transactionId
          in: path
          required: true
          description: ID of the transaction to retrieve
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Transaction retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "404":
          description: Transaction not found
        "401":
          description: Unauthorized access

    put:
      summary: Update an existing transaction
      description: Updates the details of a specific transaction.
      operationId: updateTransaction
      parameters:
        - name: budgetId
          in: path
          required: true
          description: ID of the budget the transaction belongs to
          schema:
            type: integer
            format: int64
        - name: transactionId
          in: path
          required: true
          description: ID of the transaction to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        "200":
          description: Transaction updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "400":
          description: Invalid transaction ID or request body
        "404":
          description: Transaction not found
        "401":
          description: Unauthorized access

    delete:
      summary: Delete a transaction by ID
      description: Removes a transaction from a specific budget.
      operationId: deleteTransaction
      parameters:
        - name: budgetId
          in: path
          required: true
          description: ID of the budget the transaction belongs to
          schema:
            type: integer
            format: int64
        - name: transactionId
          in: path
          required: true
          description: ID of the transaction to delete
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Transaction deleted successfully (No Content)
        "400":
          description: Invalid transaction ID
        "404":
          description: Transaction not found
        "401":
          description: Unauthorized access


  /budgets/{budgetId}/summaries:
    get:
      summary: Get budget period summary
      operationId: getBudgetSummary
      parameters:
        - name: budgetId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Budget summary
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PeriodSummary"
        "400":
          description: Invalid input
        "404":
          description: Budget not found

  /transactions/import/{budgetId}:
    post:
      summary: Import transactions from a CSV file
      operationId: importTransactions
      parameters:
        - name: budgetId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "202":
          description: Import started successfully
        "400":
          description: Invalid file format

