server:
  port: 8080

spring:
  application:
    name: fambud
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/fambud
    username: fambud
    password: fambud
    properties:
      logging.level: DEBUG
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fambud
    username: fambud
    password: fambud
  data:
    r2dbc:
      schema:
        generate: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/fambud
    user: postgres
    password: rocky
    locations: classpath:db.migration
    baseline-on-migrate: true
app:
  base-url: /api/budgets

logging:
  level:
    org.springframework: INFO
    org.springframework.dao: INFO
    org.springframework.data: INFO
    org.springframework.r2dbc: INFO
    io.r2dbc: INFO
    com.hl.fambud: INFO
